name: Python package

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Definir Python do sistema manualmente
        run: |
          echo "PYTHON_LOCATION=/usr/bin/python3.11" >> $GITHUB_ENV
          echo "PATH=$PYTHON_LOCATION/bin:$PATH" >> $GITHUB_ENV

      - name: Exibir versão do Python
        run: python3 --version

      - name: Criar ambiente virtual
        run: python3 -m venv venv

      - name: Ativar ambiente virtual e instalar dependências
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install pandas

      

